// Date: 10.05.2017 20:21:05
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class Modelorofolius extends ModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape3;
    ModelRenderer Shape3;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape7;
    ModelRenderer Shape7;
    ModelRenderer Shape7;
    ModelRenderer Shape7;
    ModelRenderer Shape8;
  
  public Modelorofolius()
  {
    textureWidth = 256;
    textureHeight = 128;
    
      Shape1 = new ModelRenderer(this, 0, 0);
      Shape1.addBox(-16F, 0F, -16F, 32, 4, 32);
      Shape1.setRotationPoint(0F, 20F, 0F);
      Shape1.setTextureSize(256, 128);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 136, 0);
      Shape2.addBox(-8F, 0F, -8F, 16, 17, 16);
      Shape2.setRotationPoint(0F, 3F, 0F);
      Shape2.setTextureSize(256, 128);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 0, 78);
      Shape3.addBox(-3F, 0F, -8.5F, 6, 19, 17);
      Shape3.setRotationPoint(-6F, 2F, 0F);
      Shape3.setTextureSize(256, 128);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0.1858931F);
      Shape3 = new ModelRenderer(this, 0, 78);
      Shape3.addBox(-3F, 0F, -8.5F, 6, 19, 17);
      Shape3.setRotationPoint(0F, 2F, 6F);
      Shape3.setTextureSize(256, 128);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 1.570796F, 0.1858931F);
      Shape3 = new ModelRenderer(this, 0, 78);
      Shape3.addBox(-3F, 0F, -8.5F, 6, 19, 17);
      Shape3.setRotationPoint(6F, 2F, 0F);
      Shape3.setTextureSize(256, 128);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 3.141593F, 0.1684398F);
      Shape3 = new ModelRenderer(this, 0, 78);
      Shape3.addBox(-3F, 0F, -8.5F, 6, 19, 17);
      Shape3.setRotationPoint(0F, 2F, -6F);
      Shape3.setTextureSize(256, 128);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, -1.570796F, 0.1684398F);
      Shape4 = new ModelRenderer(this, 62, 40);
      Shape4.addBox(-5F, -18F, -5F, 10, 18, 10);
      Shape4.setRotationPoint(0F, 2F, 0F);
      Shape4.setTextureSize(256, 128);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0F);
      Shape5 = new ModelRenderer(this, 124, 41);
      Shape5.addBox(-5.5F, -12F, -5.5F, 11, 11, 11);
      Shape5.setRotationPoint(0F, -14.8F, 0F);
      Shape5.setTextureSize(256, 128);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0F, 0F);
      Shape6 = new ModelRenderer(this, 0, 48);
      Shape6.addBox(-1.5F, -13F, -1.5F, 3, 18, 3);
      Shape6.setRotationPoint(0F, -20F, 0F);
      Shape6.setTextureSize(256, 128);
      Shape6.mirror = true;
      setRotation(Shape6, 0F, 0F, 0F);
      Shape7 = new ModelRenderer(this, 100, 102);
      Shape7.addBox(-9F, -5F, 0F, 18, 5, 0);
      Shape7.setRotationPoint(0F, 0F, 0F);
      Shape7.setTextureSize(256, 128);
      Shape7.mirror = true;
      setRotation(Shape7, 0F, 0.7853982F, 0F);
      Shape7 = new ModelRenderer(this, 100, 102);
      Shape7.addBox(-9F, -5F, 0F, 18, 5, 0);
      Shape7.setRotationPoint(0F, 0F, 0F);
      Shape7.setTextureSize(256, 128);
      Shape7.mirror = true;
      setRotation(Shape7, 0F, -0.7853982F, 0F);
      Shape7 = new ModelRenderer(this, 100, 102);
      Shape7.addBox(-9F, -5F, 0F, 18, 5, 0);
      Shape7.setRotationPoint(0F, 0F, 0F);
      Shape7.setTextureSize(256, 128);
      Shape7.mirror = true;
      setRotation(Shape7, 0F, 0.3839724F, 0F);
      Shape7 = new ModelRenderer(this, 100, 102);
      Shape7.addBox(-9F, -5F, 0F, 18, 5, 0);
      Shape7.setRotationPoint(0F, 0F, 0F);
      Shape7.setTextureSize(256, 128);
      Shape7.mirror = true;
      setRotation(Shape7, 0F, -0.3839724F, -0.0174533F);
      Shape7 = new ModelRenderer(this, 100, 102);
      Shape7.addBox(-9F, -5F, 0F, 18, 5, 0);
      Shape7.setRotationPoint(0F, 0F, 0F);
      Shape7.setTextureSize(256, 128);
      Shape7.mirror = true;
      setRotation(Shape7, 0F, 1.570796F, 0F);
      Shape8 = new ModelRenderer(this, 92, 68);
      Shape8.addBox(-7F, 0F, -7F, 14, 0, 14);
      Shape8.setRotationPoint(0F, -15.7F, 0F);
      Shape8.setTextureSize(256, 128);
      Shape8.mirror = true;
      setRotation(Shape8, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Shape1.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape3.render(f5);
    Shape3.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
    Shape5.render(f5);
    Shape6.render(f5);
    Shape7.render(f5);
    Shape7.render(f5);
    Shape7.render(f5);
    Shape7.render(f5);
    Shape7.render(f5);
    Shape8.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
