// Date: 07.05.2017 09:47:24
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.minecraft.src;

public class Modelenergizationpillar extends ModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape2;
    ModelRenderer Shape2;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
  
  public Modelenergizationpillar()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      Shape1 = new ModelRenderer(this, 0, 0);
      Shape1.addBox(-3F, 0F, -3F, 6, 16, 6);
      Shape1.setRotationPoint(0F, 8F, 0F);
      Shape1.setTextureSize(128, 64);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 108, 0);
      Shape2.addBox(-3F, 0F, -2F, 6, 17, 3);
      Shape2.setRotationPoint(0F, 8F, -2F);
      Shape2.setTextureSize(128, 64);
      Shape2.mirror = true;
      setRotation(Shape2, -0.0902614F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 108, 0);
      Shape2.addBox(-3F, 0F, -1F, 6, 17, 3);
      Shape2.setRotationPoint(0F, 8F, 2F);
      Shape2.setTextureSize(128, 64);
      Shape2.mirror = true;
      setRotation(Shape2, 0.0902684F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 108, 0);
      Shape2.addBox(-3F, 0F, -1F, 6, 17, 3);
      Shape2.setRotationPoint(2F, 8F, 0F);
      Shape2.setTextureSize(128, 64);
      Shape2.mirror = true;
      setRotation(Shape2, 0.0902684F, 1.570796F, 0F);
      Shape2 = new ModelRenderer(this, 108, 0);
      Shape2.addBox(-3F, 0F, -1F, 6, 17, 3);
      Shape2.setRotationPoint(-2F, 8F, 0F);
      Shape2.setTextureSize(128, 64);
      Shape2.mirror = true;
      setRotation(Shape2, 0.0902684F, -1.570796F, 0F);
      Shape3 = new ModelRenderer(this, 0, 47);
      Shape3.addBox(-6F, 0F, -6F, 12, 2, 12);
      Shape3.setRotationPoint(0F, 21F, 0F);
      Shape3.setTextureSize(128, 64);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Shape1.render(f5);
    Shape2.render(f5);
    Shape2.render(f5);
    Shape2.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
